export const GET_CINEMA = 'GET_CINEMA';

// CREATE SHOWTIMES FOR THE CINEMA

export const ADD_SHOWTIME_CINEMA_SUCCESSFULLY = 'ADD_SHOWTIME_CINEMA_SUCCESSFULLY'
export const ADD_SHOWTIME_CINEMA_DEPEAT = 'ADD_SHOWTIME_CINEMA_DEPEAT';