// TAKE ALL LIST MOVIES
export const GET_MOVIES = 'GET_MOVIES';

// TAKE THE WATCHING OR UPCOMMING MOVIES
export const SET_WATCHNG_FILM = 'SET_WATCHNG_FILM';
export const SET_UPCOMING_FILM = 'SET_UPCOMING_FILM';


// TAKE DETAIL FILM FOR DETAIL COMPONENT
export const GET_DETAIL_MOVIE = 'GET_DETAIL_MOVIE';

