// TAKE ALL LIST MOVIES
export const GET_MOVIES = 'GET_MOVIES';

// TAKE THE WATCHING OR UPCOMMING MOVIES
export const SET_WATCHNG_FILM = 'SET_WATCHNG_FILM';
export const SET_UPCOMING_FILM = 'SET_UPCOMING_FILM';


// TAKE DETAIL FILM FOR DETAIL COMPONENT
export const GET_DETAIL_MOVIE = 'GET_DETAIL_MOVIE';


// COMPLETED BOOKING TYPE
export const COMPLETED_BOOKING = 'COMPLETED_BOOKING';

// REDIRECT TAP ACTION TYPE
export const REDIRECT_TABS = 'REDIRECT_TABS';
// TABS ACTIVE
export const CHANGE_TAB_ACTIVE = 'CHANGE_TAB_ACTIVE';

// CHECK ORDER REAL TIME
export const ORDER_CHAIR_REAL_TIME = 'ORDER_CHAIR_REAL_TIME'
