// TAKE ALL LIST MOVIES
export const GET_MOVIES = 'GET_MOVIES';

// TAKE THE WATCHING OR UPCOMMING MOVIES
export const SET_WATCHNG_FILM = 'SET_WATCHNG_FILM';
export const SET_UPCOMING_FILM = 'SET_UPCOMING_FILM';


// TAKE DETAIL FILM FOR DETAIL COMPONENT
export const GET_DETAIL_MOVIE = 'GET_DETAIL_MOVIE';


// COMPLETED BOOKING TYPE
export const COMPLETED_BOOKING = 'COMPLETED_BOOKING';

// REDIRECT TAP ACTION TYPE
export const REDIRECT_TABS = 'REDIRECT_TABS';
// TABS ACTIVE
export const CHANGE_TAB_ACTIVE = 'CHANGE_TAB_ACTIVE';

// CHECK ORDER REAL TIME
export const ORDER_CHAIR_REAL_TIME = 'ORDER_CHAIR_REAL_TIME'

// THE INFO OF SPECIFIC MOVIES
export const GET_INFO_SPECIFIC_MOVIES = 'GET_INFO_SPECIFIC_MOVIES'

// ADD, DELETE, ERROR MESSAGE FOR CLICK EVENT

export const ADD_MOIVE_SUCCESSFULLY = 'ADD_MOIVE_SUCCESSFULLY';
export const UPDATE_MOVIE_SUCCESSFULLY = 'UPDATE_MOVIES_SUCCESSFULLY';
export const ADD_MOVIE_DEPEAT = 'ADD_MOVIE_DEPEAT';
export const UPDATE_MOVIE_DEPEAT = 'UPDATE_MOVIE_DEPEAT';