export const USER_LOGIN_ACTION = 'USER_LOGIN_ACTION';
export const TAKE_INFO_USER = 'TAKE_INFO_USER'
export const REGISGER_USER = 'REGISGER_USER';

export const LOGIN_SUCESSFULLY = 'LOGIN_SUCESSFULLY';
export const LOGIN_DEPEAT = 'LOGIN_DEPEAT';
export const REGISTER_SUCESSFULLY = 'REGISTER_SUCESSFULLY';
export const REGISTER_DEPEAT = 'REGISTER_DEPEAT';
